# SITE CONFIGURATION
baseurl:
url: "https://NSBudapest.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "NSBudapest"
  avatar: assets/img/logo.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Budapest based iOS meetup." # used by search engines

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Group of people interested in iOS and macOS development. We ❤️ quality code, testing, automation, craft beer and mad science in general.</p>
  header_text_feature_image: assets/img/header/header.jpg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a> - 2018

  # Icons
  rss:
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "NSBudapest"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "nsbudapest"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: UA-103238078-2
  disqus_shortname:
  katex: false # Enable if using math markup
  portfolio: false
  search: true
  tags: true
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Previous"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 12
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
